config/routes.rb
Rails.application.routes.draw do
  resources :identity_providers
  root 'appointments#index'
  devise_for :users
  resources :appointments

  get 'saml/init'
  get 'saml/consume'
  get 'saml/metadata'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord

  belongs_to :patient, class_name: 'User'
  belongs_to :doctor, class_name: 'User'

  default_scope { order('start_date ASC') }

  scope :for_user, ->(user) { where(patient_id: user.id).or(where(doctor_id: user.id)) }
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.for_user(current_user)
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
    if current_user.patient?
      @doctors = User.doctor
    else
      @patients = User.patient
    end
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:patient_id, :doctor_id, :start_date, :end_date)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%- if current_user.patient? %>
      <%= form.label :patient_id %>
      <%= form.number_field :patient_id, id: :appointment_patient_id, value: current_user.id, disabled: true %>
    <% else %>
      <%= form.label :patient_id %>
      <%= select 'appointment', 'patient_id', @patients.collect {|p| [ p.full_name, p.id ] } %>
    <% end -%>
  </div>

  <div class="field">
    <%- if current_user.doctor? %>
      <%= form.label :doctor_id %>
      <%= form.number_field :doctor_id, id: :appointment_doctor_id, value: current_user.id, hidden: true %>
      <%= current_user.full_name %>
    <% else %>
      <%= form.label :patient_id %>
      <%= select 'appointment', 'doctor_id', @doctors.collect {|p| [ p.full_name, p.id ] } %>
    <% end -%>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date, id: :appointment_start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date, id: :appointment_end_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Patient</th>
      <th>Doctor</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.patient.full_name %></td>
        <td><%= appointment.doctor.full_name %></td>
        <td><%= appointment.start_date %></td>
        <td><%= appointment.end_date %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient:</strong>
  <%= @appointment.patient.full_name %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @appointment.doctor.full_name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @appointment.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @appointment.end_date %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>