config/routes.rb
Rails.application.routes.draw do
  resources :identity_providers
  root 'appointments#index'
  devise_for :users
  resources :appointments

  get 'saml/init'
  get 'saml/consume'
  get 'saml/metadata'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/identity_provider.rb
class IdentityProvider < ApplicationRecord
end

app/controllers/identity_providers_controller.rb
class IdentityProvidersController < ApplicationController
  before_action :set_identity_provider, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin!

  # GET /identity_providers
  # GET /identity_providers.json
  def index
    @identity_providers = IdentityProvider.all
  end

  # GET /identity_providers/1
  # GET /identity_providers/1.json
  def show
  end

  # GET /identity_providers/new
  def new
    @identity_provider = IdentityProvider.new
  end

  # GET /identity_providers/1/edit
  def edit
  end

  # POST /identity_providers
  # POST /identity_providers.json
  def create
    @identity_provider = IdentityProvider.new(identity_provider_params)

    respond_to do |format|
      if @identity_provider.save
        format.html { redirect_to @identity_provider, notice: 'Identity provider was successfully created.' }
        format.json { render :show, status: :created, location: @identity_provider }
      else
        format.html { render :new }
        format.json { render json: @identity_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /identity_providers/1
  # PATCH/PUT /identity_providers/1.json
  def update
    respond_to do |format|
      if @identity_provider.update(identity_provider_params)
        format.html { redirect_to @identity_provider, notice: 'Identity provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @identity_provider }
      else
        format.html { render :edit }
        format.json { render json: @identity_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /identity_providers/1
  # DELETE /identity_providers/1.json
  def destroy
    @identity_provider.destroy
    respond_to do |format|
      format.html { redirect_to identity_providers_url, notice: 'Identity provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_identity_provider
      @identity_provider = IdentityProvider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def identity_provider_params
      params.require(:identity_provider).permit(:name, :requestor, :idp_entity_id, :idp_sso_target_url, :idp_slo_target_url, :idp_cert, :idp_cert_fingerprint, :idp_cert_fingerprint_algorithm)
    end

    def authorize_admin!
      redirect_to root_url unless current_user.admin?
    end
end

app/helpers/identity_providers_helper.rb
module IdentityProvidersHelper
end

app/views/identity_providers/_form.html.erb
<%= form_with(model: identity_provider, local: true) do |form| %>
  <% if identity_provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(identity_provider.errors.count, "error") %> prohibited this identity_provider from being saved:</h2>

      <ul>
      <% identity_provider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :identity_provider_name %>
  </div>

  <div class="field">
    <%= form.label :requestor %>
    <%= form.text_field :requestor, id: :identity_provider_requestor %>
  </div>

  <div class="field">
    <%= form.label 'IDP ENTITY ID' %>
    <%= form.text_field :idp_entity_id, id: :identity_provider_idp_entity_id %>
  </div>

  <div class="field">
    <%= form.label 'IDP SSO TARGET URL' %>
    <%= form.text_field :idp_sso_target_url, id: :identity_provider_idp_sso_target_url %>
  </div>

  <div class="field">
    <%= form.label 'IDP SLO TARGET URL' %>
    <%= form.text_field :idp_slo_target_url, id: :identity_provider_idp_slo_target_url %>
  </div>

  <div class="field">
    <%= form.label 'IDP CERT' %>
    <%= form.text_area :idp_cert, id: :identity_provider_idp_cert %>
  </div>

  <div class="field">
    <%= form.label 'IDP CERT FINGERPRINT' %>
    <%= form.text_field :idp_cert_fingerprint, id: :identity_provider_idp_cert_fingerprint %>
  </div>

  <div class="field">
    <%= form.label 'IDP CERT FINGERPRINT ALGORITH' %>
    <%= form.text_field :idp_cert_fingerprint_algorithm, id: :identity_provider_idp_cert_fingerprint_algorithm %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/identity_providers/edit.html.erb
<h1>Editing Identity Provider</h1>

<%= render 'form', identity_provider: @identity_provider %>

<%= link_to 'Show', @identity_provider %> |
<%= link_to 'Back', identity_providers_path %>

app/views/identity_providers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Identity Providers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Idp entity</th>
      <th>Idp sso target url</th>
      <th>Idp slo target url</th>
      <th>Idp cert</th>
      <th>Idp cert fingerprint</th>
      <th>Idp cert fingerprint algorithm</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @identity_providers.each do |identity_provider| %>
      <tr>
        <td><%= identity_provider.name %></td>
        <td><%= identity_provider.idp_entity_id %></td>
        <td><%= identity_provider.idp_sso_target_url %></td>
        <td><%= identity_provider.idp_slo_target_url %></td>
        <td><%= identity_provider.idp_cert %></td>
        <td><%= identity_provider.idp_cert_fingerprint %></td>
        <td><%= identity_provider.idp_cert_fingerprint_algorithm %></td>
        <td><%= link_to 'Show', identity_provider %></td>
        <td><%= link_to 'Edit', edit_identity_provider_path(identity_provider) %></td>
        <td><%= link_to 'Destroy', identity_provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Identity Provider', new_identity_provider_path %>

app/views/identity_providers/new.html.erb
<h1>New Identity Provider</h1>

<%= render 'form', identity_provider: @identity_provider %>

<%= link_to 'Back', identity_providers_path %>

app/views/identity_providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @identity_provider.name %>
</p>

<p>
  <strong>Requestor:</strong>
  <%= @identity_provider.requestor %>
</p>

<p>
  <strong>Idp entity:</strong>
  <%= @identity_provider.idp_entity_id %>
</p>

<p>
  <strong>Idp sso target url:</strong>
  <%= @identity_provider.idp_sso_target_url %>
</p>

<p>
  <strong>Idp slo target url:</strong>
  <%= @identity_provider.idp_slo_target_url %>
</p>

<p>
  <strong>Idp cert:</strong>
  <%= @identity_provider.idp_cert %>
</p>

<p>
  <strong>Idp cert fingerprint:</strong>
  <%= @identity_provider.idp_cert_fingerprint %>
</p>

<p>
  <strong>Idp cert fingerprint algorithm:</strong>
  <%= @identity_provider.idp_cert_fingerprint_algorithm %>
</p>

<%= link_to 'Edit', edit_identity_provider_path(@identity_provider) %> |
<%= link_to 'Back', identity_providers_path %>